In [1]:
from __future__ import print_function
import torch

# create Tensor

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  1.1715e-42],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-2.5873e+19,  8.5199e-43,  0.0000e+00],
        [ 0.0000e+00,  9.1843e-41,  0.0000e+00],
        [-3.6519e+19,  8.5199e-43,  0.0000e+00]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.5570,  0.0466,  0.7503],
        [ 0.4028,  0.8213,  0.4994],
        [ 0.3292,  0.6227,  0.7079],
        [ 0.3003,  0.9557,  0.8142],
        [ 0.2309,  0.0508,  0.1289]])


In [8]:
x= torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [9]:
type(x)

torch.Tensor

In [11]:
x= torch.tensor([5.5,3])
print(x)

tensor([ 5.5000,  3.0000])


In [13]:
x=x.new_ones(5,3)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [15]:
x= torch.rand_like(x,dtype=torch.float32)
print(x)

tensor([[ 0.7308,  0.4404,  0.0859],
        [ 0.6787,  0.1348,  0.8773],
        [ 0.8580,  0.6648,  0.6566],
        [ 0.1172,  0.6904,  0.0463],
        [ 0.4566,  0.1145,  0.1712]])


In [17]:
print(x.size())

torch.Size([5, 3])


In [19]:
print(type(x.size()))

<class 'torch.Size'>


# operation

In [20]:
y = torch.rand(5, 3)


In [21]:
x + y


tensor([[ 0.7684,  0.8688,  0.8195],
        [ 0.9071,  0.2000,  0.9105],
        [ 1.6911,  1.3826,  1.2188],
        [ 0.8135,  1.5638,  0.9379],
        [ 0.6869,  0.8702,  0.2494]])

In [22]:
print(torch.add(x,y))

tensor([[ 0.7684,  0.8688,  0.8195],
        [ 0.9071,  0.2000,  0.9105],
        [ 1.6911,  1.3826,  1.2188],
        [ 0.8135,  1.5638,  0.9379],
        [ 0.6869,  0.8702,  0.2494]])


In [24]:
result =torch.empty(5,3)
print(torch.add(x,y,out=result))

tensor([[ 0.7684,  0.8688,  0.8195],
        [ 0.9071,  0.2000,  0.9105],
        [ 1.6911,  1.3826,  1.2188],
        [ 0.8135,  1.5638,  0.9379],
        [ 0.6869,  0.8702,  0.2494]])


In [25]:
y.add_(x)   # _ will change the value  y

tensor([[ 0.7684,  0.8688,  0.8195],
        [ 0.9071,  0.2000,  0.9105],
        [ 1.6911,  1.3826,  1.2188],
        [ 0.8135,  1.5638,  0.9379],
        [ 0.6869,  0.8702,  0.2494]])

In [26]:
print(x[:,1])

tensor([ 0.4404,  0.1348,  0.6648,  0.6904,  0.1145])


In [27]:
import numpy as np

In [30]:
a = np.ones(5)
print(a)


[ 1.  1.  1.  1.  1.]


In [39]:
b = torch.from_numpy(a)
print(b)


tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


# Tensor for CUDA

In [38]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to('cpu',torch.double))

tensor([[ 1.7308,  1.4404,  1.0859],
        [ 1.6787,  1.1348,  1.8773],
        [ 1.8580,  1.6648,  1.6566],
        [ 1.1172,  1.6904,  1.0463],
        [ 1.4566,  1.1145,  1.1712]], device='cuda:0')
tensor([[ 1.7308,  1.4404,  1.0859],
        [ 1.6787,  1.1348,  1.8773],
        [ 1.8580,  1.6648,  1.6566],
        [ 1.1172,  1.6904,  1.0463],
        [ 1.4566,  1.1145,  1.1712]], dtype=torch.float64)


#Auto grad